apiVersion: v1
kind: Template
metadata:
  annotations:
    description: CoolStore Microservices - Inventory Template
    tags: microservice,nginx
  name: inventory-mockup
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: inventory
    name: inventory
  spec:
    tags:
      - from:
          kind: DockerImage
          name: 'docker.io/siamaksade/rhsummit18-cloudnative-inventory:latest'
        name: latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: inventory
    name: inventory
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    selector:
      app: inventory
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: inventory
    name: inventory
  spec:
    port:
      targetPort: http
    to:
      kind: Service
      name: inventory
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: inventory
    name: inventory
  spec:
    replicas: 1
    selector:
      version: v1
      deploymentconfig: inventory
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: inventory
          version: v1
          deploymentconfig: inventory
      spec:
        containers:
        - env:
          - name: SERVICE_DELAY
            value: "${SERVICE_DELAY}"
          image: inventory
          imagePullPolicy: IfNotPresent
          name: inventory
          ports:
          - containerPort: 8080
            protocol: TCP
            name: http
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - inventory
        from:
          kind: ImageStreamTag
          name: inventory:latest
      type: ImageChange
    - type: ConfigChange
parameters:
  - displayName: Service Name
    name: SERVICE_NAME
    required: true
    value: inventory
  - displayName: Service Delay in ms
    name: SERVICE_DELAY
    required: false
    value: "100"